# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Connect.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Connect(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(405, 176)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_ip = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ip.setGeometry(QtCore.QRect(84, 76, 171, 36))
        self.lineEdit_ip.setObjectName("lineEdit_ip")
        self.lineEdit_port = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_port.setGeometry(QtCore.QRect(308, 76, 71, 36))
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.label_ip = QtWidgets.QLabel(self.centralwidget)
        self.label_ip.setGeometry(QtCore.QRect(8, 81, 81, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_ip.setFont(font)
        self.label_ip.setObjectName("label_ip")
        self.label_port = QtWidgets.QLabel(self.centralwidget)
        self.label_port.setGeometry(QtCore.QRect(264, 83, 66, 19))
        self.label_port.setObjectName("label_port")
        self.label_inf = QtWidgets.QLabel(self.centralwidget)
        self.label_inf.setGeometry(QtCore.QRect(73, 20, 261, 20))
        self.label_inf.setAlignment(QtCore.Qt.AlignCenter)
        self.label_inf.setObjectName("label_inf")
        self.pushButton_connect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_connect.setGeometry(QtCore.QRect(135, 130, 121, 36))
        self.pushButton_connect.setObjectName("pushButton_connect")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Подключение к серверу"))
        self.label_ip.setText(_translate("MainWindow", "Адрес(IP):"))
        self.label_port.setText(_translate("MainWindow", "Порт:"))
        self.label_inf.setText(_translate("MainWindow", "Введите данные для подключения"))
        self.pushButton_connect.setText(_translate("MainWindow", "Подключиться"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Connect()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
