# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Server.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Server(object):
    def setupUi(self, MainWindow,):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(645, 420)
        MainWindow.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget_people = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_people.setGeometry(QtCore.QRect(10, 20, 621, 351))
        self.listWidget_people.setObjectName("listWidget_people")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


