from PyQt5 import QtCore, QtWidgets


class Ui_Server(object):
    def setupUi(self, MainWindow, ):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1059, 662)
        MainWindow.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(9, 10, 1041, 641))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.pushButton_show_all_usr = QtWidgets.QPushButton(self.page)
        self.pushButton_show_all_usr.setGeometry(QtCore.QRect(407, 160, 221, 36))
        self.pushButton_show_all_usr.setObjectName("pushButton_show_all_usr")
        self.pushButton_crt_user = QtWidgets.QPushButton(self.page)
        self.pushButton_crt_user.setGeometry(QtCore.QRect(433, 200, 171, 36))
        self.pushButton_crt_user.setObjectName("pushButton_crt_user")
        self.stackedWidget.addWidget(self.page)
        self.page_usr = QtWidgets.QWidget()
        self.page_usr.setObjectName("page_usr")
        self.listWidget_people = QtWidgets.QListWidget(self.page_usr)
        self.listWidget_people.setGeometry(QtCore.QRect(10, 0, 1021, 351))
        self.listWidget_people.setStyleSheet("color: rgb(50, 50, 50);\n"
                                             "")
        self.listWidget_people.setObjectName("listWidget_people")
        self.pushButton_back_main_page_usr = QtWidgets.QPushButton(self.page_usr)
        self.pushButton_back_main_page_usr.setGeometry(QtCore.QRect(470, 360, 103, 36))
        self.pushButton_back_main_page_usr.setObjectName("pushButton_back_main_page_usr")
        self.stackedWidget.addWidget(self.page_usr)
        self.page_crt_usr = QtWidgets.QWidget()
        self.page_crt_usr.setObjectName("page_crt_usr")
        self.label_login = QtWidgets.QLabel(self.page_crt_usr)
        self.label_login.setGeometry(QtCore.QRect(600, 80, 66, 19))
        self.label_login.setAlignment(QtCore.Qt.AlignCenter)
        self.label_login.setObjectName("label_login")
        self.pushButton_save = QtWidgets.QPushButton(self.page_crt_usr)
        self.pushButton_save.setGeometry(QtCore.QRect(230, 550, 191, 36))
        self.pushButton_save.setObjectName("pushButton_save")
        self.label_passw = QtWidgets.QLabel(self.page_crt_usr)
        self.label_passw.setGeometry(QtCore.QRect(600, 130, 66, 19))
        self.label_passw.setAlignment(QtCore.Qt.AlignCenter)
        self.label_passw.setObjectName("label_passw")
        self.lineEdit_login = QtWidgets.QLineEdit(self.page_crt_usr)
        self.lineEdit_login.setGeometry(QtCore.QRect(690, 70, 321, 36))
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.lineEdit_pass = QtWidgets.QLineEdit(self.page_crt_usr)
        self.lineEdit_pass.setGeometry(QtCore.QRect(690, 120, 321, 36))
        self.lineEdit_pass.setObjectName("lineEdit_pass")
        self.lineEdit_passw_2 = QtWidgets.QLineEdit(self.page_crt_usr)
        self.lineEdit_passw_2.setGeometry(QtCore.QRect(690, 175, 321, 36))
        self.lineEdit_passw_2.setObjectName("lineEdit_passw_2")
        self.label_passw_2 = QtWidgets.QLabel(self.page_crt_usr)
        self.label_passw_2.setGeometry(QtCore.QRect(503, 180, 171, 19))
        self.label_passw_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_passw_2.setObjectName("label_passw_2")
        self.label_info = QtWidgets.QLabel(self.page_crt_usr)
        self.label_info.setGeometry(QtCore.QRect(360, 20, 321, 20))
        self.label_info.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info.setObjectName("label_info")
        self.pushButton_back_main_page_crt_usr = QtWidgets.QPushButton(self.page_crt_usr)
        self.pushButton_back_main_page_crt_usr.setGeometry(QtCore.QRect(630, 550, 191, 36))
        self.pushButton_back_main_page_crt_usr.setObjectName("pushButton_back_main_page_crt_usr")
        self.label_fio = QtWidgets.QLabel(self.page_crt_usr)
        self.label_fio.setGeometry(QtCore.QRect(10, 80, 66, 19))
        self.label_fio.setAlignment(QtCore.Qt.AlignCenter)
        self.label_fio.setObjectName("label_fio")
        self.lineEdit_fio = QtWidgets.QLineEdit(self.page_crt_usr)
        self.lineEdit_fio.setGeometry(QtCore.QRect(100, 70, 321, 36))
        self.lineEdit_fio.setObjectName("lineEdit_fio")
        self.lineEdit_phone = QtWidgets.QLineEdit(self.page_crt_usr)
        self.lineEdit_phone.setGeometry(QtCore.QRect(100, 175, 321, 36))
        self.lineEdit_phone.setObjectName("lineEdit_phone")
        self.lineEdit_post = QtWidgets.QLineEdit(self.page_crt_usr)
        self.lineEdit_post.setGeometry(QtCore.QRect(100, 120, 321, 36))
        self.lineEdit_post.setObjectName("lineEdit_post")
        self.lineEdit_mail = QtWidgets.QLineEdit(self.page_crt_usr)
        self.lineEdit_mail.setGeometry(QtCore.QRect(100, 220, 321, 36))
        self.lineEdit_mail.setObjectName("lineEdit_mail")
        self.label_phone = QtWidgets.QLabel(self.page_crt_usr)
        self.label_phone.setGeometry(QtCore.QRect(8, 180, 66, 19))
        self.label_phone.setAlignment(QtCore.Qt.AlignCenter)
        self.label_phone.setObjectName("label_phone")
        self.label_post = QtWidgets.QLabel(self.page_crt_usr)
        self.label_post.setGeometry(QtCore.QRect(0, 130, 91, 20))
        self.label_post.setAlignment(QtCore.Qt.AlignCenter)
        self.label_post.setObjectName("label_post")
        self.label_mail = QtWidgets.QLabel(self.page_crt_usr)
        self.label_mail.setGeometry(QtCore.QRect(8, 226, 71, 19))
        self.label_mail.setAlignment(QtCore.Qt.AlignCenter)
        self.label_mail.setObjectName("label_mail")
        self.stackedWidget.addWidget(self.page_crt_usr)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton_show_all_usr.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(1))
        self.pushButton_crt_user.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(2))
        self.pushButton_back_main_page_usr.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(0))
        self.pushButton_back_main_page_crt_usr.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(0))
        self.pushButton_crt_user.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(2))
        self.pushButton_crt_user.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(2))
        self.pushButton_save.clicked.connect(self.crt_new_user)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_show_all_usr.setText(_translate("MainWindow", "Просмотр всех пользователей"))
        self.pushButton_crt_user.setText(_translate("MainWindow", "Создать пользователя"))
        self.pushButton_back_main_page_usr.setText(_translate("MainWindow", "Назад"))
        self.label_login.setText(_translate("MainWindow", "Логин:"))
        self.pushButton_save.setText(_translate("MainWindow", "Сохранить"))
        self.label_passw.setText(_translate("MainWindow", "Пароль:"))
        self.label_passw_2.setText(_translate("MainWindow", "Подтвердите пароль:"))
        self.label_info.setText(_translate("MainWindow", "Создание пользователя"))
        self.pushButton_back_main_page_crt_usr.setText(_translate("MainWindow", "Отмена"))
        self.label_fio.setText(_translate("MainWindow", "ФИО:"))
        self.label_phone.setText(_translate("MainWindow", "Телефон:"))
        self.label_post.setText(_translate("MainWindow", "Должность:"))
        self.label_mail.setText(_translate("MainWindow", "Эл.почта:"))